version: 2
jobs:
  build:
    machine: true
    environment:
      PJ_NAME: 'formio-app-formio'
      FORK_URL: 'https://github.com/formio'
      ORIG_URL: 'https://github.com/eole-repos'
    steps:
      - add_ssh_keys: 
          fingerprints:
                  - 'f0:77:80:d7:33:77:d3:f3:68:78:f6:76:52:ce:31:7b'
      - checkout
      - run: git clone $FORK_URL/$PJ_NAME
      - run: echo "git clone $FORK_URL/$PJ_NAME"
      - run: cd  $PJ_NAME
        #- run: echo "cd  $PJ_NAME"
      - run: git remote add upstream $ORIG_URL/$PJ_NAME
        #- run: echo "git remote add upstream $ORIG_URL/$PJ_NAME"
      - run: git checkout master
      - run: git pull --no-edit upstream master
      - run: git push origin master
workflows: 
  version: 2
  cron_workflow: 
    triggers:
      - schedule:
          # UTC+0
          cron: "0 16 * * *"
          filters:
            branches:
              only: 
                - master
    jobs: 
      - build
  normal_workflow: 
     jobs: 
      - build

